name: 'Setup Clojure'
description: 'Setup your runner with Clojure build tools'
author: 'DeLaGuardo'
branding:
  icon: 'gift'
  color: 'blue'
inputs:
  lein:
    description: 'The Leiningen version to make available on the path.'
  boot:
    description: 'The boot-clj version to make available on the path.'
  tools-deps:
    description: '[DEPRECATED] The tools deps version to make available on the path.'
    deprecationMessage: 'Use the `cli` input instead'
  cli:
    description: 'Clojure CLI version to make available on the path.'
  cmd-exe-workaround:
    description: >+
      On Windows platform, it will replace official Clojure CLI
      with the `deps.clj` of its specific version, `latest` can be used.

      Useful for running `clojure` command from `cmd.exe`.
  bb:
    description: 'Babashka version to install, `latest` can be used.'
  clj-kondo:
    description: 'Clj-kondo version to install, `latest` can be used.'
  cljstyle:
    description: 'cljstyle version to install, `latest` can be used.'
  zprint:
    description: 'zprint version to install, `latest` can be used.'
  github-token:
    description: >+
      To fix rate limit errors, provide `secrets.GITHUB_TOKEN` value to this field.
      More info: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    default: ${{ github.token }}
    required: false
  invalidate-cache:
    description: >+
      Set to `true` to fix problems realted to wrongly populated tool cache
    default: false
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
  pre: 'dist/index.js'
  post: 'dist/index.js'
