name: Test Amazon corretto JDK

on: [push]

jobs:
  corretto-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Install all the tools
        uses: ./
        with:
          cli: 1.12.0.1488
          clj-kondo: 2023.12.15
          cljstyle: 0.15.0

      - name: Check Clojure CLI
        run: clojure -Sdescribe

      - name: Check clj-kondo version
        run: clj-kondo --version

      - name: Check cljstyle version
        run: cljstyle version
