name: Test OS leiningen
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: env
      - name: Install leiningen
        uses: ./
        with:
          lein: 2.10.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: env
      - run: DEBUG=true lein -v
