name: No Auth test

on:
  push:
    branches:
      - main

jobs:
  no-auth-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install all the tools
        uses: ./
        with:
          cli: latest
          lein: latest
          boot: latest
          bb: latest
          clj-kondo: latest
          cljstyle: latest
          zprint: latest

          # Explicit empty string should trigger "no auth" workflow
          # this will not set Authorisation header for any GitHub API http calls
          github-token: ''

      - name: Check Clojure CLI
        run: clojure -Sdescribe

      - name: Check leiningen version
        run: lein version

      - name: Check boot version
        run: boot -V

      - name: Check babashka version
        run: bb --version

      - name: Check clj-kondo version
        run: clj-kondo --version

      - name: Check cljstyle version
        run: cljstyle version

      - name: Check zprint version
        run: zprint --version
