name: Smoke tests

on: [push]

jobs:

  # Deprecated version identifier
  # Please use `cli: version` as in job `clojure-cli`
  test-tools-deps:

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools-deps
        # uses: DeLaGuardo/setup-clojure@master
        uses: ./
        with:
          tools-deps: 1.10.1.693

      - name: Execute clojure code
        run: clojure -e "(+ 1 1)"

  clojure-cli:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools-deps
        # uses: DeLaGuardo/setup-clojure@master
        uses: ./
        with:
          cli: 1.10.1.693

      - name: Execute clojure code on Linux and MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: clojure -e "(+ 1 1)"
        shell: bash

      - name: Execute clojure code on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: clojure -e "(+ 1 1)"
        shell: powershell

  test-leiningen:

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        # uses: DeLaGuardo/setup-clojure@master
        uses: ./
        with:
          lein: 2.9.1

      - name: Check leiningen version
        run: lein version

  test-boot:

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install boot
        # uses: DeLaGuardo/setup-clojure@master
        uses: ./
        with:
          boot: 2.8.3

      - name: Check boot version
        run: boot -V
