name: Smoke tests

on: [push]

jobs:

  test-tools-deps:

    runs-on: ubuntu-latest

    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.1.469

      - name: Execute clojure code
        run: clojure -e "(+ 1 1)"

  test-leiningen:

    runs-on: ubuntu-latest

    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1

      - name: Check leiningen version
        run: lein -v

  test-boot:

    runs-on: ubuntu-latest

    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          boot: 2.8.3

      - name: Check boot version
        run: boot -V

  test-all-together-with-latest-versions:

    runs-on: ubuntu-latest

    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install all the tools together
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          lein: latest
          boot: latest

      - name: Run checks
        run: |
          clojure -e "(+ 1 1)"
          lein -v
          boot -V
